### ISSUE TITLE
Strange rsc-macro-transformer behaviour

### ISSUE THREAD

**Issue by arkoort** [ashinn/chibi-scheme#738] opened 2021-04-05 14:56 UTC
This code fails in Mit scheme (`;Unbound variable: y`) but works in Chibi scheme (`4`). I understand why it doesn't work in Mit. But I don't understand why it works in Chibi.

And more, if I change `(c t f)` in one of `make-syntactic-closure` parameters to `(define)` (which identifier isn't used in the macro at all), it works too. In Chibi. It fails only with empty free identifiers list. Is this behavior correct?

```scheme

(define-syntax aif
  (rsc-macro-transformer
   (lambda (form macro-env)
     (let ((c (cadr form))
           (t (caddr form))
           (f (cadddr form)))
       (make-syntactic-closure macro-env '(c t f)
         `(let ((it ,c))
            (if it ,t ,f)))))))

(let ((x 1) (y 2))
  (aif (+ x y) (+ it x) (- it y)))
```

**Comment by mnieper** [comment] 2021-04-05 15:24
What do you try to achieve with the list (c t f)? This list is only
relevant for identifiers appearing in the form that is being closed over.
But your quasiquotation doesn't produce any identifier named "c", "t", or
"f".

PS I would advise against using the syntactic closure macro facility as it
doesn't work well together with syntax-rules (or generally in nested macro
contexts). For example, the macro

(define-syntax loop
  (sc-macro-transformer
   (lambda (exp env)
     (let ((body (cdr exp)))
       `(call-with-current-continuation
         (lambda (exit)
           (let f ()
             ,@(map (lambda (exp)
                      (make-syntactic-closure env '(exit)
                        exp))
                    body)
             (f))))))))

(stolen from MIT/GNU Scheme's documentation) breaks when used as part of
another macro expansion.

Am Mo., 5. Apr. 2021 um 16:57 Uhr schrieb arkoort ***@***.***

**Comment by arkoort** [comment] 2021-04-05 15:46
It was an erroneous translation of
```scheme
(define-syntax aif
  (sc-macro-transformer
   (lambda (form usage-env)
     (let ((c (close-syntax (cadr form) usage-env))
           (t (make-syntactic-closure usage-env '(it) (caddr form)))
           (f (make-syntactic-closure usage-env '(it) (cadddr form))))
       `(let ((it ,c))
          (if it ,t ,f))))))
```

At first I got it working, and just at second I understood that it is totally incorrect. But works.

Yes, I've read your post about the limitations of the syntactic closures. I just try to understand this facility better, because it's new to me.

**Comment by mnieper** [comment] 2021-04-05 15:52
Am Mo., 5. Apr. 2021 um 17:46 Uhr schrieb arkoort ***@***.***
>:

>  I just try to understand this facility better, because it's new to me.


I still have to finish SRFI 211 where the feature is going to be documented
as well.

PS In my Unsyntax implementation, your original code fails as well (as
expected).

**Comment by ashinn** [comment] 2021-04-06 05:42
I like the general idea of syntactic-closures, but it is underspecified and underdocumented, and I believe the current MIT version has some refinements to the original paper.

But if I understand correctly, there is no bug here and we can close the issue?

**Comment by mnieper** [comment] 2021-04-06 06:26
Am Di., 6. Apr. 2021 um 07:42 Uhr schrieb Alex Shinn <
***@***.***>:

> I like the general idea of syntactic-closures, but it is underspecified
> and underdocumented, and I believe the current MIT version has some
> refinements to the original paper.
>
The problem with syntactic closures is that they are not expressive enough
for robust unhygienic macros. There are also limits to what kind of macro
output this facility can produce. For example, it is impossible to write a
macro that produces a lambda with two formal arguments X and Y where X is
closed in the user and Y is closed in the macro environment if I remember
my earlier experiments correctly.

So underspecification is only one of the problems.

> But if I understand correctly, there is no bug here and we can close the
> issue?
>
In the code in the original post, the identifiers of the output of the aif
macro are all closed in the macro transformer environment where 'x' and 'y'
are unbound. So Chibi should have produced errors because of unbound
variables 'x' and 'y'.

So something is not right with Chibi's implementation. (The example in the
original post is a bit confusing because the macro claims to be 'aif' but
is instead some random test case.)

**Comment by ashinn** [comment] 2021-04-06 08:23
Given that there is no specification, I was speaking of syntactic closures in the broadest sense: macro transformers which work by closing expressions in explicit environments, optionally with some way to specify which bindings are unhygienic.

This is in contrast to the underlying R6RS macro expander, which operates on opaque syntax objects, with APIs for extracting expressions from and binding expressions to those objects.

At this level the definition is so vague that I cannot accept a statement that it is impossible to do anything.  In particular, your X and Y parameters in different envs example sounds suspicious even given existing implementations.

Chibi implements closures by chaining the expanded environments, so that the 'x' and 'y' are in fact visible in cases like this where a macro-env closure is wrapped in a user-env closure.  Thus this is working as intended, and shows some of the flexibility in my very broad definition of syntactic closures.  Possibly you can find real-world examples where this would break, but I implemented it once a very long time ago and have since lost almost all interest in unhygienic macros, never once having had the need to use one.  So "fixing" this is a low priority that I wouldn't consider without some formal syntactic-closures standard.

I should probably clarify in the docs that this is _not_ the MIT Scheme syntactic-closures though.

**Closed by ashinn** 2021-04-06 08:23 UTC
