### ISSUE TITLE
make test-all fails on macos (at show test)

### ISSUE THREAD

**Issue by mbamac** [ashinn/chibi-scheme#662] opened 2020-06-26 21:37 UTC
show: ....................................................................
    ..........................................................................
    ...........................x..............................................
    ..........................................................................
    ...!!!!!!!!!.....!...............
    312 out of 323 (96.6%) tests passed in 0.5455338954925537 seconds.
    1 failure (0.3%).
    10 errors (3.1%).
    FAIL: (show #f (numeric/si 3986))
        expected "3.9Ki" but got "4k"
    on line 266 of file "lib/chibi/show-test.sld"
    ERROR: (show #f (show-columns (list displayed "abc\ndef\n")))
        ERROR on line 576 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 576 of file "lib/chibi/show-test.sld"
    ERROR: (show #f (show-columns (list displayed "abc\ndef\n") (list disp...
        ERROR on line 578 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 578 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list displayed "abc\ndef\n") (list displayed "123\n456\n")))
    ERROR: (show #f (show-columns (list displayed "abc\ndef\n") (list disp...
        ERROR on line 581 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 581 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list displayed "abc\ndef\n") (list displayed "123\n456")))
    ERROR: (show #f (show-columns (list displayed "abc\ndef") (list displa...
        ERROR on line 584 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 584 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list displayed "abc\ndef") (list displayed "123\n456\n")))
    ERROR: (show #f (show-columns (list displayed "abc\ndef\nghi\n") (list...
        ERROR on line 587 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 587 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list displayed "abc\ndef\nghi\n") (list displayed "123\n456\n789\n")))
    ERROR: (show #f (show-columns (list displayed "abc\ndef\n") (list disp...
        ERROR on line 590 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 590 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list displayed "abc\ndef\n") (list displayed "123\n456\n") (list displayed "wuv\nxyz\n")))
    ERROR: (show #f (show-columns (list (lambda (x) (padded/right 5 x)) "a...
        ERROR on line 594 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 594 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list (lambda (x) (padded/right 5 x)) "abc\ndef\n") (list displayed "123\n456\n")))
    ERROR: (show #f (show-columns (list (lambda (x) (upcased (padded/right...
        ERROR on line 598 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 598 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list (lambda (x) (upcased (padded/right 5 x))) "abc\ndef\n") (list displayed "123\n456\n")))
    ERROR: (show #f (show-columns (list (lambda (x) (padded/right 5 (upcas...
        ERROR on line 602 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 602 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list (lambda (x) (padded/right 5 (upcased x))) "abc\ndef\n") (list displayed "123\n456\n")))
    ERROR: (show #f (show-columns (list (lambda (x) (padded/right 36 x)) (...
        ERROR on line 660 of file lib/chibi/show-test.sld: undefined variable: show-columns
    on line 658 of file "lib/chibi/show-test.sld"
(show #f (show-columns (list (lambda (x) (padded/right 36 x)) (with ((width 36)) (pretty '(define (fold kons knil ls) (let lp ((ls ls) (acc knil)) (if (null? ls) acc (lp (cdr ls) (kons (car ls) acc)))))))) (list (lambda (x) (each " ; " x)) (with ((width 36)) (wrapped "The fundamental list iterator.  Applies KONS to each element of LS and the result of the previous application, beginning with KNIL.  With KONS as CONS and KNIL as '(), equivalent to REVERSE.")))))
    show c: ............................................................
    60 out of 60 (100.0%) tests passed in 0.3960719108581543 seconds.
    system: .................
    17 out of 17 (100.0%) tests passed in 0.004544973373413086 seconds.
    tar: ...............
    15 out of 15 (100.0%) tests passed in 0.0067751407623291016 seconds.
    uri: ..........................................
    42 out of 42 (100.0%) tests passed in 0.006367921829223633 seconds.
5422 out of 5433 (99.8%) tests passed in 3.464102029800415 seconds.
1 failure (0.0%).
10 errors (0.2%).

**Comment by ashinn** [comment] 2020-06-26 22:13
This is just a duplicate of the SRFI 166 tests, and not kept in sync.  Removed it.

**Closed by ashinn** 2020-06-26 22:13 UTC
