### ISSUE TITLE
`make test-all' fails without 'make install'

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#501] opened 2018-12-05 11:14 UTC
Running `make test-all` in the source directory may fail if a previous system-wide installation of Chibi is present. Workarounds are either running `make uninstall` or `make install` prior running the tests. Both should not be needed.

(I know hat saying this may be fruitless, but using Automake would yield more robust Makefiles... Next time I will just say: "Ceterum censeo Carthaginem esse delendam", and you'll know what I mean. ;-))

**Comment by ashinn** [comment] 2018-12-05 14:20
I don't see how automake could possibly help here.

**Comment by mnieper** [comment] 2018-12-05 14:46
> I don't see how automake could possibly help here.

Not automatically, of course. :-) However, Automake already knows how to, say, create 'distcheck' targets that build the source and install it in a pristine temporary directory. I'm not saying that this functionality cannot be coded by hand, but it is more error-prone, I think. (`distcheck` works by playing with the `--prefix` flag.)

Anyway, to resolve the single issue reported here, it is hopefully enough to make sure that the right flags are set here: https://github.com/ashinn/chibi-scheme/blob/d513bdc9776a0847485f01e36d92a03942763fa1/Makefile#L18.

**Comment by ashinn** [comment] 2018-12-05 15:01
I've seen this issue before and tend to make uninstall.  The problem is probably with the chibi module path, which automake knows nothing about - the corresponding fix (whatever the correct args in that line are) would work just as well without automake.

**Comment by ashinn** [comment] 2018-12-05 16:55
The pushed fix should work, let me know if this happens again for you.

**Closed by ashinn** 2018-12-05 16:55 UTC
