### ISSUE TITLE
(chibi process) seems to have a leak somewhere.

### ISSUE THREAD

**Issue by lockywolf** [ashinn/chibi-scheme#739] opened 2021-04-09 10:20 UTC
MWE:

```
chibi-scheme -R
(import (chibi process))
(define (a x) 
(process->string "getfattr --no-dereference --only-values -n user.lwf.mindmap.skip-grandchildren .") 
(display x) (newline) 
(a (+ x 1)))
> (a 0)
```

Almost the same code using `system?` seems to have no problem.

Crashes after about 110 runs.

**Comment by ashinn** [comment] 2021-04-09 10:37
Sounds like a duplicate of issue #735.  Are you running from head?

**Comment by lockywolf** [comment] 2021-04-09 11:31
Sorry, on chibi from head this problem does not appear.
However, the semantic of `-r` seems to have changed.

MWE:
```
/tmp/chibi# cat ./test.scm 
#!/usr/bin/chibi-scheme -rnewermain

(import (chibi))

(define (newermain . args)
  (display args)
  (newline))

root@delllaptop:/tmp/chibi# ./test.scm 
(("newermain" "./test.scm"))
```

I don't thing the name of the "main" was in "args" about 10 commits ago.

**Comment by lockywolf** [comment] 2021-04-09 11:49
The behaviour has changed in:

```
lockywolf@delllaptop:~/OfficialRepos/chibi-scheme$ git bisect good
ac698ce6aef7c29d2ec7349717c2bef043c82082 is the first bad commit
commit ac698ce6aef7c29d2ec7349717c2bef043c82082
Author: Lassi Kortela <lassi@lassi.io>
Date:   Mon Feb 1 21:29:26 2021 +0200

    Re-implement SRFI 193 (Command line)

 main.c | 26 +++++++++++++++++---------
 1 file changed, 17 insertions(+), 9 deletions(-)
```

Is the new one staying or is it a bug?

**Comment by ashinn** [comment] 2021-04-09 12:55
The new behavior is consistent with SRFI 22:

> Upon invocation of a script, the Scheme system calls a procedure named main with one argument, a list of strings containing the Unix command-line arguments to the script, i.e. the elements of the argv vector of the Scheme script interpreter process from index 1 on. Thus, the first element of the list is the name of the script.

I think the old behavior was more convenient - who cares what the script is named, and you can always look it up separately if needed - but I'm outvoted.

I'll close this issue, feel free to raise a new one if you want to continue discussing the SRFI 22 semantics.

**Closed** 2021-04-09 12:55 UTC
