### ISSUE TITLE
Identifiers in library body are not resolved in a satisfying fashion

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#399] opened 2017-03-08 15:22 UTC
Consider the following library:
```scheme
(define-library (lib)
  (export quux)
  (import (scheme base))
  (begin
    (define-syntax foo
      (syntax-rules ()
	((foo) (bar))))
    (define (quux)
      (foo))
    (define (bar)
      42)))
```
Chibi does not resolve the identifier `bar`:
```bash
$ chibi-scheme -mlib -e'(quux)'
WARNING: reference to undefined variable: #<SC 139869749613664 bar>
ERROR in quux on line 7 of file ./lib.sld: undefined variable: #<SC 139869749613664 bar>
Searching for modules exporting #<SC 139869749613664 bar> ...
... none found.
```

The problem disappears when the procedures `quux` and `bar` are ordered the other way round.

**Comment by ashinn** [comment] 2017-03-11 01:03
Thanks!  Will take a look.

**Comment by mnieper** [comment] 2017-03-21 09:19
I think this here may be related:
```scheme
(import (scheme base)
	(scheme write))

(define-syntax foo
  (syntax-rules ()
    ((foo bar)
     (begin
       (define (bar) (baz))
       (define (baz) 42)))))

(define (baz) 43)

(foo quux)

(display (quux))
(newline)
```

This program display `43` as `(foo quux)` does not insert a new binding for (renamed) `baz`, but `set!`s the existing binding. On the other hand, Larceny reports `42` when running this program. (And Larceny does not complain about the original code this issue is about.)

**Comment by ashinn** [comment] 2017-03-22 03:21
Not really a related issue.  The `baz` defined by `foo` will be hygienically renamed, but this will resolve to the same binding as the previous `baz`.  Re-defining the same identifier acting as `set!` is intentional, and is what you expect in most cases.  For `define` (as opposed to `set!` or other references), we could consider not resolving to an existing `identifier=?` binding and adding a new binding.  I'd have to think about that if you expect this second example to behave like Larceny.

I should have said before, I know exactly why the bug in your first example happens, and just haven't decided the best way to handle it.  Chibi analyzes the body single-pass, left-to-right, and when it encounters an unknown identifier it creates a special empty binding, which would later be filled-in by the appropriate definition.  It resolves synclo references by checking for that exact binding, and unwrapping and recursing in the synclo env if not found.  If never found, this is an unknown identifier and we create the empty binding _for the original wrapped synclo_.  The later definition is then for an unwrapped binding, which does not resolve to the synclo binding, so the previous empty reference is not filled in.

**Closed** 2017-03-26 12:19 UTC

**Comment by mnieper** [comment] 2017-04-03 06:17
The commit does not generally resolve the issue. For the following example program, Chibi complains about an undefined variable `#<SC 139823242476416 #<SC 139823242374592 qux>>`:

```scheme
(import (scheme base)
        (scheme write))

(define-syntax baz
  (syntax-rules ()
    ((baz foo)
     (define-syntax foo
       (syntax-rules ()
	 ((foo bar)
	  (define (bar) (qux))))))))

(baz foo)

(foo bar)

(define (qux) 42)

(display (bar))
(newline)
```

I tested the above code with other Scheme implementations. Larceny, Scheme48, Guile and Gambit get it right.

**Comment by ashinn** [comment] 2017-04-03 06:50
Oops, that was careless, fixed for multiple levels of synclos.

How do you run for Gambit?  Last I checked it didn't have functioning R7RS support.

**Comment by mnieper** [comment] 2017-04-03 07:03
I just took the R5RS part of the example omitting the imports when I tested with non-R7RS implementations. So no wizardry here. :-)

**Comment by mnieper** [comment] 2017-04-03 12:44
I have tested your fix and I have run into another issue:
```scheme
(import (scheme base)
	(scheme write))

(define bar #f)

(define-syntax foo
  (syntax-rules ()
    ((foo bar)
     (define (bar) (baz)))))


(define-syntax qux
  (syntax-rules ()
    ((qux)
     (begin
       (define (baz) 43)))))

(foo bar)
(qux)
(define (baz) 42)

(write (bar))
(newline)
```

Chibi displays `43` (as opposed to `42`). This is a violation of hygiene as specified in 4.3 of the R7RS. Macro-expanding `(qux)` inserts a new binding for the identifier `baz`. Accordingly, it has to be renamed (and should not interfere with the later binding of `baz` occurring at the top-level).

Exchanging the two lines `(qux)` and `(define (baz) 42)` make the program display `42`. Thus, the expansion of `(qux)` suddenly becomes hygienic again.

**Comment by mnieper** [comment] 2017-04-03 13:21
P.S.: This seems to be related to your second comment in this thread.

**Comment by ashinn** [comment] 2017-04-03 14:12
[OK, then gambit and guile both use psyntax so should behave the same.]

Everything gets renamed, it's a question of when renamed identifiers should resolve to each other.  Your example expands to:

```
(foo bar)            ; (define (bar) (baz.0))  ; unbound reference
(qux)                ; (define (baz.1) 43)     ; bind baz.0?
(define (baz) 42)    ; (define (baz) 42)     ; bind baz.0?
```

These are all identifier=? before the bindings (baz.1 and baz) are inserted.  After they are inserted, baz.1 and baz.0 would not resolve to each other.  Maybe another argument for bound-identifier=?, but I'll push a simpler fix that I think should be correct in all cases, and think on this a little more.

**Comment by mnieper** [comment] 2017-04-03 15:22
I had to time to take a look at your latest fix.That fix cannot handle the following code:

```scheme
(import (scheme base)
	(scheme write))

(define-syntax wrapper
  (syntax-rules ()
    ((wrapper)
     (begin
       (define-syntax foo
	 (syntax-rules ()
	   ((foo x)
	    (define (x) (y)))))

       (foo x)
       (define (y) 42)

       (write (x))
       (newline)))))

(wrapper)
```

(I am also thinking of a clean solution for the problem.)

**Comment by mnieper** [comment] 2017-04-03 15:37
Here is another test code (that works with Scheme48, Guile, Larceny):

```scheme
(import (scheme base)
	(scheme write))

(define-syntax foo
  (syntax-rules ()
    ((foo c) 
     (begin
       (define (a) (b)) ; (R)
       (define (c) 'fail) ; (F)
       (define (b) 'ok) ; (O)
       (write (a))
       (newline)))))

(foo b)
```

Unfortunately, Chibi's current algorithm yields `fail`, not `ok`. At the moment, I don't see how the current algorithm can be modified to cover all cases: Consider the example. When Chibi encounters the line marked `(F)`, it tries to decide whether to patch the unbound reference to `b` in the line marked `(R)`. However, this decision depends on whether the line `(O)` is in the code or not. If `(O)` is part of the code (as in the example), the unbound reference to `(b)` should not be patched before Chibi expands the line marked `(O)`. On the other hand, when removing the line `(O)`, the unbound reference to `b` has already to be patched when the line marked `(F)` is encountered.

**Comment by ashinn** [comment] 2017-04-04 09:34
Thanks!  That's interesting.  Your example is a paradox.

All of this works as expected inside a let, because chibi groups leading definitions and delays analyzing their values.  However, by design the repl, programs and library bodies are all treated the same, which means it _must_ be a single pass.  Consider your example at a repl where we interleave writes between definitions:

```scheme
(define (a) (b)) ; (R)
(define (c) 'fail) ; (F)
(write (a)) (newline)
(define (b) 'ok) ; (O)
(write (a)) (newline)
```

The first call to (write (a)) must either resolve to 'fail, or an undefined value error.  If it's an error, then anything goes and this is not a valid example.  Otherwise, we either get what you consider to be the wrong binding, or we get the wrong binding temporarily and the retroactively change it!

**Comment by mnieper** [comment] 2017-04-04 10:41
Using explicit `write`s to make things more clear is a good idea!

I think there is a solution to the paradox. The repl has only to be single pass with respect to the top-level `begin` form resulting from the expansion of `(foo b)`, not with respect to the forms inside the `begin` form. So the `begin` form could be expanded into something like the following (where variable references to the internal defines are resolved lazily).
```scheme
(let-syntax/splicing ()
  (define (a) (b))
  (define (c) 'fail)
  (define dummy1 (write (a)))
  (define (b) 'ok)
  (define dummy2 (write (a))
  (define dummy3 (newline))
  (if #f #f))
```
Due to delayed reference resolving, evaluating the initializer for `dummy1` (using the letrec*-semantics) will result in an undefined value error, so the above code is invalid. So your example code may do whatever it wants to do.

A fix for the original issue could thus be to wrap every top-level command or definitions into a `let-syntax/splicing`-form (where expressions and definitions may be mixed freely and where an expression-less body is allowed) before expanding it.

**Comment by mnieper** [comment] 2017-04-04 15:24
Here is more code to think about/experiment with:
```scheme
(define-syntax foo
  (syntax-rules ()
    ((foo c) 
     (begin
       (define (b) 'original)           ; (O)
       (define (a) (b))                 ; (R)
       (write (a))
       (newline)
       (define-syntax b                 ; (S)
	 (syntax-rules ()
	   ((b) 'syntax)))
       (define (c) 'fail)               ; (F)
       (define (b) 'new)		; (N)
       (write (a))
       (newline)))))
					
(foo b)
```

I do get the following results:

- Guile (psyntax) prints syntax, syntax.
- Scheme48 prints original, new.
- Chibi prints original, original.
- Larceny prints original, new.

**Comment by mnieper** [comment] 2017-04-04 18:20
Even more experiments:
```scheme
(define-syntax foo
  (syntax-rules ()
    ((foo c) 
     (begin
       (define (a) (b))                 ; (R)
       (define-syntax b                 ; (S)
	 (syntax-rules ()
	   ((b) 'syntax)))
       (define (c) 'ok)                 ; (C)
       (write (a))                      ; (A)
       (newline)))))
					
(foo b)
```

Results:
- Guile prints syntax
- Scheme48 prints syntax
- Larceny prints ok
- Chibi complains about undefined variable `#<SC ... b>`
- MIT/GNU Scheme prints syntax

Without using a macro:
```scheme
(begin
  (define (a) (b))                 ; (R)
  (define-syntax b                 ; (S)
    (syntax-rules ()
      ((b) 'syntax)))
  (define (c) 'ok)                 ; (C)
  (write (a))                      ; (A)
  (newline))
```

Results:
- Guile prints syntax
- Scheme48 prints syntax
- Larceny complains about `b` denoting a macro
- Chibi complains about undefined variable `b`
- MIT/GNU Scheme prints syntax

**Comment by ashinn** [comment] 2017-04-05 13:57
I'd consider special processing for the expansion of a single top-level begin, but won't let library/program bodies diverge from the repl behavior.  So I'm ok if Chibi diverges from other impls in some corner cases.  I need to think a little about how much I want to support.

**Comment by mnieper** [comment] 2017-04-05 16:00
I you implement special processing for the expansion of a single top-level `begin`, you can use that implementation as well for library/program bodies. In fact, you would have to because at top-level, a single `begin` has to be equivalent to the sequence of commands and definitions enclosed by the `begin`.

R4RS, IEEE Scheme, and R5RS specify the semantics of program bodies as follows (R5RS version, emphasis mine): "Definitions and syntax definitions occurring at the top level of a program can be interpreted _declaratively_. They cause bindings to be created in the top level environment or modify the value of existing top-level bindings. Expressions occurring at the top level of a program are interpreted imperatively; they are executed in order when the program is invoked or loaded, and typically perform some kind of initialization."

While there is some room for interpretation, the most plausible interpretation is that a top-level program has to be scanned for definitions first before any expression is evaluated (and, if not at top-level, expanded). This is what Scheme48, MIT/GNU Scheme, Larceny and Guile, for example, do. The following top-level code prints `42`:
```scheme
(begin
  (define (a) (b))
  (define-syntax b
    (syntax-rules ()
      ((b)
       42)))
  (write (a))
  (newline))
```

R6RS is much clearer on the semantics of the top-level. But essentially it is the same as above. The top-level forms are expanded in order to recognize definitions. After all definitions are recognized, the right-hand-sides of the definitions are expanded and evaluated.

R7RS is very vague about the top level semantics, much vaguer than R5RS. However, it does not state that it wants to explicitely diverge in top-level behaviour from R6RS (or R5RS) in programs and libraries. Thus it makes most sense to have R7RS implementations whose top-level semantics are compatible with R5RS and R6RS, that is that they show the same behaviour as MIT Scheme, Guile, Larceny, Scheme 48.

**Comment by ashinn** [comment] 2017-04-06 12:58
R7RS is intentionally vague on this point.  In Chibi running a program is equivalent to typing the same commands at the repl.  Importing a library is, modulo name conflicts, equivalent to splicing the library body into the program or repl.  This minimizes surprises and has many advantages for debugging.

That's what I mean by Chibi treats these the same by design - it wasn't an oversight, it was very deliberate.  Unless someone has a real-life example where they are hindered by this with no easy workaround, I have no intention of changing it.

Your original example I can imagine coming up easily in programs, so I made the changes to support that, but we're increasingly getting into vague corner cases that I'm not even sure should be allowed.

**Comment by mnieper** [comment] 2017-04-06 13:42
I believe that Chibi's behaviour at top-level (repl semantics) is compatible with R5RS and R6RS as long as all top-level syntax definitions appear in the program text before their uses and as long as top-level syntax definitions are not redefined later in the program text as variable definitions. So for most practical purposes, it is not hard to write programs in a way that works equally well with either Chibi or any of the other implementations. (Whether the benefits of Chibi's design outweigh the drawback that its design differs from implementations that were already around when R5RS was the current standard, is another question.)

Leaving out the corner cases where R7RS is more liberal than R5RS/R6RS, we still have the following example. Here, Chibi's current behaviour is definitely a violation of hygiene, which mandates that the behaviour of the following code should not depend on the naming of the variable named `b` in the macro's template:

```scheme
(import (scheme base)
	(scheme write))

(define-syntax foo
  (syntax-rules ()
    ((foo c) 
     (begin
       (define (a) (b)) ; (R)
       (define (c) 'fail) ; (F)
       (define (b) 'ok) ; (O)
       (write (a))
       (newline)))))

(foo b)
```

**Comment by ashinn** [comment] 2017-04-06 14:24
Again, I consider this example a paradox and don't necessarily agree it is well defined.  Even if it were I would consider deviating from the standard to preserve repl semantics.

As discussed, I could special case this by handling begin blocks, but there may be other cases that don't involve a single begin.  If it makes the implementation complicated, doesn't handle all cases, and the cases it does handle are not likely to occur in practice, it's not worth it.

**Comment by mnieper** [comment] 2017-04-06 15:13
I don't see what makes this example non well-defined by the R7RS. While this example may look artificial, it occurs whenever a programmer defines a macro expanding into a, say, procedure definition (visible at top-level) together with a number of definitions of helper procedures that call each other recursively.

As long as this is not fixed and hygiene thus not preserved, a programmer has to make sure that no top-level identifier is reused in a macro template when it is intended to be inserted as a bound identifier. (E.g. in the above example, I have to rename `b` by hand because `b` is already used outside the macro at top-level.) While this is certainly possible (although it may lead to surprises when hygiene is implicitly assumed), I don't see how to do a general renaming by hand when macros expanding into macros are involved.

Anyway, while I would appreciate if you could correct the above behaviour eventually, there is still a much urgent error in Chibi's implementation. Take a look at the following code:
```scheme
(define-syntax define-odd?
  (syntax-rules ()
    ((define-odd? odd? even?)
     (define (odd? n)
       (not (even? (- n 1)))))))

(define-syntax define-even?
  (syntax-rules ()
    ((define-even? even? odd?)
     (define (even? n)
       (or (zero? n)
	   (not (odd? n)))))))

(define-odd? odd? even?)
(define-even? even? odd?)

(write (even? 2))
(newline)
```

Chibi prints, incorrectly, `#f`. When the definitions `(define-odd? odd? even?)` and `(define-even? even? odd?)` are exchanged, Chibi suddenly prints `#t`.

**Comment by ashinn** [comment] 2017-04-10 13:55
As pointed out, interleaving writes in your example exposes it as "an error".

Nonetheless, I've tentatively pushed an alternate way of handling this by deferring resolving the binding as long as possible.  I may still revert this - I've been busy and haven't had any proper time to spend on this - but at least it preserves the equivalence of the repl and programs.

The new example is clearly unrelated and should be a new bug.  If it really is a bug?  At first glance your definition of odd? is incorrect, it should be (even? (- n 1)), not (not (even? (- n 1))).

Also one thing to be aware of in such examples is Chibi actually inlines many primitive operations eagerly - if you want to rename them you have to rename them in advance or not import them.

**Comment by ashinn** [comment] 2017-04-10 14:00
... of course, this is only really a limitation of the chibi repl, since redefinition is disallowed in libraries and programs by 5.2:

> In a program or library declaration, it is an error to import the same identifier more than once with different bindings, or to redefine or mutate an imported binding with a definition or with set!, or to refer to an identifier before it is imported.

**Comment by mnieper** [comment] 2017-04-11 05:45
> As pointed out, interleaving writes in your example exposes it as "an error".

I think we agree that the following should not be considered an error at top-level:
```scheme
(define (f x)
  (if (even? x) (g x) 'odd))
(define (g x)
  (if (odd? x) (f x) 'even))
(f 10)
```

On the other hand, the following is clearly an error:
```scheme
(define (f x)
  (if (even? x) (g x) 'odd))
(f 10)
(define (g x)
  (if (odd? x) (f x) 'even))
```

In other words: that something becomes an error when interleaved with `write`s does not at all mean that the original code is an error. In particular, there is nothing in R7RS (and R5RS and R6RS)  that forbids the code you are calling a paradox.

**Comment by mnieper** [comment] 2017-04-11 05:56
> The new example is clearly unrelated and should be a new bug. If it really is a bug? At first glance your definition of odd? is incorrect, it should be (even? (- n 1)), not (not (even? (- n 1))).

> Also one thing to be aware of in such examples is Chibi actually inlines many primitive operations eagerly - if you want to rename them you have to rename them in advance or not import them.

Thanks for catching this. I missed to exclude `even?` and `odd?` from the imports when running my example as a program. So it is not a bug. (And, yes, I got the arithmetics wrong; there was one `not` too much; but this was irrelevant.)

Shall I file a new bug report about the limitation of Chibi's repl when it comes to redefining imports?

**Comment by ashinn** [comment] 2017-04-12 00:10
I thought there was an open issue for this, but apparently not, go ahead and create one.

**Comment by mnieper** [comment] 2017-04-12 08:16
> I thought there was an open issue for this, but apparently not, go ahead and create one.
Did so; see #403.

**Comment by johnwcowan** [comment] 2021-01-07 01:59
> I believe that Chibi's behaviour at top-level (repl semantics) is compatible with R5RS and R6RS as long as all top-level syntax definitions appear in the program text before their uses

R7RS explicitly makes use before definition an error (for syntax, not for variables); see 5.4.

> and as long as top-level syntax definitions are not redefined later in the program text as variable definitions.

I believe this is implicitly an error also.

**Comment by ashinn** [comment] 2021-01-08 03:22
I'm not sure what may have prompted interest in this old ticket, but John is correct.  The relevant sections are 5.3.2:

>   [...] it is an error if it is not possible to evaluate each
>   <expression> of every internal definition in a <body> without
>   assigning or referring to the value of the corresponding <variable>
>   or the <variable> of any of the definitions that follow it in
>   <body>.

and

>  It is an error to define the same identifier more than once in the same <body>.

and from 5.4:

> [...] it is an error for a definition to define an identifier whose
> binding has to be known in order to determine the meaning of the
> definition itself, or of any preceding definition that belongs to
> the same group of internal definitions.

There's a fair bit of room left to interpretation in that last one, and I'm not
interested in any grey area cases that may touch on this unless they're from
a real-world program.

Looking at the last examples reported, the even? case violates redefinition
of imported bindings.  Changing this to my-even?, my-odd? and fixing the
logic bug, it works as expected in current head.

The example before that also works:

```
(import (scheme base) (scheme write))

(define-syntax foo
  (syntax-rules ()
    ((foo c) 
     (begin
       (define (a) (b)) ; (R)
       (define (c) 'fail) ; (F)
       (define (b) 'ok) ; (O)
       (write (a))
       (newline)))))

(foo b)
```

If anyone believes there are still some cases which do not fall into the error situations and are not working as expected, it's probably best to open a new bug.

**Comment by johnwcowan** [comment] 2021-01-08 22:35
It came up in a discussion of how it is that Chibi doesn't require anything like Chicken's `define-for-syntax`, but makes all defined functions in a library available in low-level macro expansions.  (Note that this is independent of phasing _between_ libraries.)
