### ISSUE TITLE
cdar error from snow-chibi

### ISSUE THREAD

**Issue by WillClinger** [ashinn/chibi-scheme#264] opened 2015-06-06 12:38 UTC
After installing version 0.7.3:
```
% snow-chibi install --impls=larceny "(chibi test)"
ERROR in cdar on line 7 of file /usr/local/share/chibi/init-7.scm: cdr: not a pair: #<Config 139755223531520>
  called from <anonymous> on line 316 of file /usr/local/share/chibi/chibi/app.scm
  called from <anonymous> on line 356 of file /usr/local/share/chibi/chibi/app.scm
  called from any1 on line 75 of file /usr/local/share/chibi/init-7.scm
  called from <anonymous> on line 128 of file /usr/local/share/chibi/chibi/app.scm
  called from <anonymous> on line 1039 of file /usr/local/share/chibi/init-7.scm
  called from <anonymous> on line 542 of file /usr/local/share/chibi/init-7.scm
  called from <anonymous> on line 622 of file /usr/local/share/chibi/init-7.scm
```

**Comment by ashinn** [comment] 2015-06-06 13:20
This had been reported and fixed in a3f5b10d62fb8c5190ce3ac8059457da9b8ef5d1.

It's technically not a bug - command-level options and subcommand-level options are in separate namespaces.  Since the --impls option is command-level, it belongs before the subcommand, i.e.:

$ snow-chibi --impls=larceny install "(chibi test)"

which works in 0.7.3.  However, I had intended the parser to fall back (assuming the
option was not shadowed), and so this works now.

**Closed by ashinn** 2015-06-06 13:20 UTC

**Comment by WillClinger** [comment] 2015-06-06 14:02
Thanks.  With the corrected order, the attempt now fails because it prompts for a sudo password.  I'm running it from an account that doesn't have sudo privileges, and I don't want to switch to an account that does because I don't want `snow-chibi` to do anything that would require sudo privileges.  I just want to install into my working copy of Larceny.

If the `--impls` option should come before the `install` command, then the example at http://snow-fort.org/doc/install should be corrected.

**Comment by ashinn** [comment] 2015-06-06 14:14
You can specify the installation directory with:

  snow-chibi --install-prefix=$HOME/wherever --impls=larceny install "(chibi test)"

You can also specify a different remote repository (optionally a local file instead of a url), which is how the snow-chibi test suite is implemented.

I'll add some examples of this to the docs, and also fix the order of --impls in the examples (thanks!).

**Comment by ashinn** [comment] 2015-06-06 14:17
Or more simply use --install-source-dir=wherever to install scheme source in the given directory instead of assuming any layout.

**Comment by ashinn** [comment] 2015-06-06 15:10
... however, if you have the "larceny" command in your path, it should have determined the installed location from that, and assuming you have write permissions not called sudo.  So that would be a bug.
