### ISSUE TITLE
Number parser

### ISSUE THREAD

**Issue by mnieper** [ashinn/chibi-scheme#331] opened 2016-05-10 06:22 UTC
I have found a few more issues with the number parser:

```
$ chibi-scheme -R
> +nan.0+i
ERROR: undefined variable: |+nan.0+i|
Searching for modules exporting |+nan.0+i| ...
... none found.
ERROR on line 1: invalid infinity: "+inf.0@0"
> +inf.0@0
```

The first one should probably parse as a number. The second one should also parse as a number. (As a side node: in this case, Chibi printed the error above the line I entered and swallowed the newline.)

Now, the following is debatable:
```
$ chibi-scheme -R
> +nan.0x
ERROR: undefined variable: |+nan.0x|
Searching for modules exporting |+nan.0x| ...
... none found.
ERROR on line 1: invalid infinity: "+inf.0x"
> +inf.0x
```

The first one seems to be correct by the standard as written (but not when using the interpretation you gave in #276). In any case, the second one should be parsed in the same way as the first. Everything else seems counter-intuitive.

**Comment by mnieper** [comment] 2016-05-11 11:08
More strange/inconsistent behaviour:
```
$ chibi-scheme -R
> #e1e400
10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
> #e1e400+1e400i
+nan.0++nan.0i
> 1e100+1e100i
1e+100+1e+100i
> #e1e100+1e100i
3.4819269584662e+99+9.37422981667873e+99i
> #e1e1@1e1i
#f
> 
```

**Comment by ashinn** [comment] 2016-05-11 13:52
+nan.0+i is unsupported by design - there should be no complex NaNs in chibi.

I'd prefer keeping the chibi number parsing simpler and not explicitly reject +nan.0x as an identifier, since it's allowed by the standard and won't cause confusion in any real program.

The extreme approximateness of #e1e100+1e100i is also allowed by the standard.  If you can convince me this is useful for real programs I'm might do something about it.

#e1e1@1e1i is invalid syntax, thow the error could be better.

The only actual bugs are +inf.0@0 and #e1e400+1e400i.

**Comment by mnieper** [comment] 2016-05-11 14:19
The reader would have to signal an error for `#e1e1@1e1i`, wouldn't it?

I can make the example of `#e1e100+1e100i` less extreme:

```
> #e1e1+1e1i
-5.10781843936852-8.5971036279928i
```

And what about the following?
```
> #e1e0+1e0i
#f
> 1e0+1e1i
0+10000000000.0i
> 1e0+1e0i
ERROR on line 1: missing imaginary part of complex: 1.0
```

**Comment by ashinn** [comment] 2016-05-11 14:22
The reader never really has to signal any errors.  I've pushed a fix for the actual bugs.

**Closed by ashinn** 2016-05-11 14:22 UTC

**Comment by mnieper** [comment] 2016-05-11 14:34
Your patch doesn't include solutions to the set of problems I posted last, does it? (The behaviour of `#e1e0+1e0i` changed, though.)

I am also wondering why you write that the reader does not have to signal any errors. Maybe I misunderstand something, but 1.3.2 in the report says something about "an error is signaled" and 6.13.2 refers to this phrase. To be honest, I haven't checked whether the `(read)` procedure would have returned `#f` as well and have silently assumed that it returns the same as the REPL.

**Comment by ashinn** [comment] 2016-05-11 14:49
6.13.2 only requires an error to be signaled for incomplete input.  Other cases are "is an error" for which we can do whatever we want.

I believe I've fixed all the actual bugs except 1e0i which would be a huge effort for the current parser, and isn't something a human would ever naturally write in a program.

**Comment by mnieper** [comment] 2016-05-11 15:01
Thanks a lot for your quickness in fixing the actual bugs and your explanation of how the signalling of the read-error is supposed to work. Out of curiosity: how does the parser actually produce the funny value of `1e0+1e1i` (which, again, no human but me would write :-) !) Or the value of `#e1e1+1e1i` compared with `#e10+10i`?
